create pkg-config .pc file when installing (with cmake >= 3.12)
carnegierobotics/LibMultiSense pull request #114
Opened 2023-03-16 16:46 UTC by wdouglass

This makes libmultisense easier to integrate with multiple (cmake and non-cmake) build systems

2023-03-16 17:22 UTC, oamidi reviewed
Hi. 

I rather not comment on anything libmultisense related.
I don't use it and know just enough about it to be dangerous.

Please rely on Matt A and Patrick Smith to comment.

Thanks
-- Omead

2023-03-16 19:15 UTC, jyakubik requested changes
Really only the description needs fixed... otherwise looks fine

2023-04-18 18:35 UTC, wdouglass commented on CMakeLists.txt
> +
I think so -- it's harmless, and some crazy person may use pkgconfig under msys or something

2023-04-18 18:43 UTC, jyakubik commented on CMakeLists.txt
> +if (${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.12")
That's fair...

2023-04-18 18:45 UTC, jyakubik commented on CMakeLists.txt
> +
i hope we never have to support a mingw build under windows...

2023-04-18 18:47 UTC, jyakubik approved these changes

2023-04-18 19:10 UTC, mattalvarado commented
Built and tested locally. This works for me!

2023-04-18 19:11 UTC, merged