Add preliminary support for aux camera calibration
carnegierobotics/LibMultiSense pull request #17
Opened 2020-09-15 05:46 UTC by mattalvarado

Add initial support for the color aux camera calibration. This aux calibration data will need to written to flash in the firmware.

2020-09-15 15:25 UTC, Nyarmith requested changes

2020-09-15 15:25 UTC, Nyarmith commented on source/LibMultiSense/details/wire/SysCameraCalibrationMessage.h
> +
too much whitespace?

2020-09-15 15:25 UTC, Nyarmith commented on source/Utilities/ImageCalUtility/ImageCalUtility.cc
> +        memset (&c.aux.D[0], 0, sizeof (c.right.D));
should it be `sizeof (c.aux.D)` ?

2020-09-15 15:25 UTC, Nyarmith commented on source/Utilities/ImageCalUtility/example_extrinsics.yml
> +
extra newline?

2020-09-15 15:25 UTC, Nyarmith commented on source/Utilities/ImageCalUtility/example_intrinsics.yml
> +
same

2020-09-15 15:29 UTC, mattalvarado commented on source/Utilities/ImageCalUtility/ImageCalUtility.cc
> +        memset (&c.aux.D[0], 0, sizeof (c.right.D));
Good catch. Thanks

2020-09-15 16:52 UTC, psmithcrl commented on source/Utilities/ImageCalUtility/ImageCalUtility.cc
> +    writeMatrix (stream, "M3", 3, 3, &calibration.aux.M[0][0]);
Do we need to check version here, what about uniots without aux imagers?

2020-09-15 16:55 UTC, psmithcrl reviewed
Just general questions about version for calibration, not sure if we need to add the explicit check for backwards compatibility.

2020-09-15 16:55 UTC, psmithcrl commented on source/Utilities/ImageCalUtility/ImageCalUtility.cc
> +    writeMatrix (stream, "R3", 3, 3, &calibration.aux.R[0][0]);
Do we need to check version here, what about units without aux imagers?

2020-09-15 18:17 UTC, psmithcrl approved these changes

2020-09-15 19:08 UTC, psmithcrl requested changes
As I was going through the other side, I realized the version in SysGetCameraCalibrationMessage should also be updated to match else client won't be able to read the aux calibration.

2020-09-15 20:48 UTC, mattalvarado commented
> As I was going through the other side, I realized the version in SysGetCameraCalibrationMessage should also be updated to match else client won't be able to read the aux calibration.

Not sure what you mean. That version should be independent of the `SysCameraCalibration` versioning. The firmware should just populate everything if it can.

2020-09-16 13:17 UTC, psmithcrl commented
> > As I was going through the other side, I realized the version in SysGetCameraCalibrationMessage should also be updated to match else client won't be able to read the aux calibration.
> 
> Not sure what you mean. That version should be independent of the `SysCameraCalibration` versioning. The firmware should just populate everything if it can.



> > As I was going through the other side, I realized the version in SysGetCameraCalibrationMessage should also be updated to match else client won't be able to read the aux calibration.
> 
> Not sure what you mean. That version should be independent of the `SysCameraCalibration` versioning. The firmware should just populate everything if it can.

I see, sorry for the confusion.

2020-09-16 13:21 UTC, psmithcrl approved these changes

2020-09-16 15:04 UTC, mattalvarado commented
@Nyarmith can you take another look at this and make sure it is good?

2020-09-16 16:30 UTC, Nyarmith approved these changes
LGTM

2020-09-16 16:48 UTC, merged