Better buffer allocation handling logic
carnegierobotics/LibMultiSense pull request #88
Opened 2022-08-16 20:32 UTC by mattalvarado

Reduce the massive amount of memory we allocate on startup for each channel instance

2022-08-16 21:07 UTC, jyakubik requested changes

2022-08-16 21:07 UTC, jyakubik commented on source/LibMultiSense/details/channel.cc
> +            i++;
We're incrementing i twice on each successful allocation, for a net result of only allocating half as many buffers as we want... I think the correct thing is to remove the increment from the for loop, and increment only after a successful allocation

2022-08-16 21:07 UTC, jyakubik commented on source/LibMultiSense/details/channel.cc
> +                throw e;
Do we want throw e here, or do we want to rethrow the exception... there might be some subtle performance or context changes depending on what we do

2022-08-16 21:07 UTC, jyakubik commented on source/LibMultiSense/details/channel.cc
> +        throw e;
Do we want throw e here, or do we want to rethrow the exception... there might be some subtle performance or context changes depending on what we do

2022-08-16 23:38 UTC, mattalvarado commented on source/LibMultiSense/details/channel.cc
> +    {
Yeah, this was my bad. Was porting over a old patch and missed that detail

2022-08-16 23:39 UTC, mattalvarado commented on source/LibMultiSense/details/channel.cc
> +    uint32_t largeBufferRetry = 0;
yes we should!

2022-08-16 23:39 UTC, mattalvarado commented on source/LibMultiSense/details/channel.cc
> +                throw e;
I figured this was a rare enough case throwing e was fine.

2022-08-16 23:40 UTC, mattalvarado commented on source/LibMultiSense/details/channel.cc
> +        throw e;
I also figured this was rare enough that we could just throw e

2022-08-17 14:37 UTC, jyakubik commented on source/LibMultiSense/details/channel.cc
> +                throw e;
agreed... i'm not sure it really matters because getting a backtrace from the point of the original throwing of the exception is hard (impossible?) under c++.

2022-09-12 21:46 UTC, jyakubik approved these changes
Looks good from here

2022-09-13 00:12 UTC, jyakubik commented on source/LibMultiSense/include/MultiSense/details/storage.hh
> +                    delete it2->second;
Is this delete safe? This implies that operator new was used to allocate memory for storage, but that call is outside the control of this class.

2022-09-13 17:32 UTC, merged